### ISSUE TITLE
请问微信自动跳转浏览器还能解决么

### ISSUE THREAD

**Issue by xingline** [wind-stone/blog#5]
请问微信自动跳转浏览器还能解决么，之前是安卓自动跳转ios弹窗，但最近微信更新后不能自动跳转了，你有解决办法么，我是nginx和php，付费解决谢谢

**Comment by wind-stone** [comment]
> 请问微信自动跳转浏览器还能解决么，之前是安卓自动跳转ios弹窗，但最近微信更新后不能自动跳转了，你有解决办法么，我是nginx和php，付费解决谢谢

可以参考下忆天网络的实现，http://www.aerae.cn/
